### ISSUE TITLE
貌似会曝出以下的问题

### ISSUE THREAD

**Issue by git-life-everywhere** [xaoxuu/hexo-theme-volantis#6]
>> 26|   <%- feed_tag(config.feed.path, {title: config.title}) %>
    27|   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    28|
    29|   <link rel="shortcut icon" href="<%= config.shortcut_icon %>" />

Cannot read property 'path' of undefined
    at eval (eval at compile (D:\MyBlog\CoolqiBlog\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:44:38)
    at returnedFn (D:\MyBlog\CoolqiBlog\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\MyBlog\CoolqiBlog\blog\node_modules\hexo\lib\theme\view.js:120:22)
    at Theme._View.View.View.renderSync (D:\MyBlog\CoolqiBlog\blog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (D:\MyBlog\CoolqiBlog\blog\node_modules\hexo\lib\plugins\helper\partial.js:39:15)
    at Object.wrapper [as partial] (D:\MyBlog\CoolqiBlog\blog\node_modules\lodash\lodash.js:4935:19)
    at eval (eval at compile (D:\MyBlog\CoolqiBlog\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:9:17)
    at returnedFn (D:\MyBlog\CoolqiBlog\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\MyBlog\CoolqiBlog\blog\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (D:\MyBlog\CoolqiBlog\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at _compiled.then.result (D:\MyBlog\CoolqiBlog\blog\node_modules\hexo\lib\theme\view.js:40:23)
    at tryCatcher (D:\MyBlog\CoolqiBlog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\MyBlog\CoolqiBlog\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\MyBlog\CoolqiBlog\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\MyBlog\CoolqiBlog\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\MyBlog\CoolqiBlog\blog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\MyBlog\CoolqiBlog\blog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\MyBlog\CoolqiBlog\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\MyBlog\CoolqiBlog\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\MyBlog\CoolqiBlog\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)

**Comment by git-life-everywhere** [comment]
这个我找到原因了，我更新了其他的一些插件，貌似不支持一些插件的最新版本。。
