### ISSUE TITLE
【问题】：执行hexo -g出现ERROR Render HTML failed报错

### ISSUE THREAD

**Issue by AyMeow** [xaoxuu/hexo-theme-volantis#917]
### 检查清单

- [X] 已经搜索过，没有发现类似 issue。
- [X] 已经搜索过[主题文档](https://volantis.js.org/)，没有发现相关内容。
- [X] 已经尝试使用过[最新版](https://github.com/volantis-x/hexo-theme-volantis/releases)，问题依旧存在。

### 主题版本

5.x

### 复现地址

无

### 问题描述

完全新建的环境，只更改了主题，其余什么都没有改
![微信截图_20240328153029](https://github.com/volantis-x/hexo-theme-volantis/assets/101166982/2281bb8f-0e91-483e-ae65-caefdbd6afe8)
ERROR Render HTML failed: archives/2024/index.html
RangeError: E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\layout\layout.ejs:36
    34|     </div>
    35|     <div>
 >> 36|       <%- partial('_partial/scripts/index') %>
    37|       <% if (theme.plugins.pjax.enable){ %>
    38|         <%- partial('_plugins/pjax/index') %>
    39|       <% } %>

E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\layout\_partial\scripts\index.ejs:146
    144|
    145| <% if (theme.structured_data && theme.structured_data.enable) { %>
 >> 146|   <%- structured_data() %>
    147| <% } %>
    148|
    149|

Incorrect locale information provided
    at new DateTimeFormat (<anonymous>)
    at module.exports (E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\breadcrumblist.js:68:19)
    at E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\index.js:28:52
    at Array.map (<anonymous>)
    at module.exports (E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\index.js:28:41)
    at eval ("E:\\Personal_Profile\\Blog\\node_modules\\hexo-theme-volantis\\layout\\_partial\\scripts\\index.ejs":267:17)
    at index (E:\Personal_Profile\Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:120:32)
    at _View.renderSync (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:62:29)
    at Object.partial (E:\Personal_Profile\Blog\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("E:\\Personal_Profile\\Blog\\node_modules\\hexo-theme-volantis\\layout\\layout.ejs":65:17)
    at layout (E:\Personal_Profile\Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:123:67)
    at _View.render (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:48:21)
    at E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:55:31
    at tryCatcher (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\async.js:86:9)
ERROR Render HTML failed: archives/2024/03/index.html
RangeError: E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\layout\layout.ejs:36
    34|     </div>
    35|     <div>
 >> 36|       <%- partial('_partial/scripts/index') %>
    37|       <% if (theme.plugins.pjax.enable){ %>
    38|         <%- partial('_plugins/pjax/index') %>
    39|       <% } %>

E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\layout\_partial\scripts\index.ejs:146
    144|
    145| <% if (theme.structured_data && theme.structured_data.enable) { %>
 >> 146|   <%- structured_data() %>
    147| <% } %>
    148|
    149|

Incorrect locale information provided
    at new DateTimeFormat (<anonymous>)
    at module.exports (E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\breadcrumblist.js:68:19)
    at E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\index.js:28:52
    at Array.map (<anonymous>)
    at module.exports (E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\index.js:28:41)
    at eval ("E:\\Personal_Profile\\Blog\\node_modules\\hexo-theme-volantis\\layout\\_partial\\scripts\\index.ejs":267:17)
    at index (E:\Personal_Profile\Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:120:32)
    at _View.renderSync (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:62:29)
    at Object.partial (E:\Personal_Profile\Blog\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("E:\\Personal_Profile\\Blog\\node_modules\\hexo-theme-volantis\\layout\\layout.ejs":65:17)
    at layout (E:\Personal_Profile\Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:123:67)
    at _View.render (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:48:21)
    at E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:55:31
    at tryCatcher (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\async.js:86:9)
ERROR
RangeError: E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\layout\layout.ejs:36
    34|     </div>
    35|     <div>
 >> 36|       <%- partial('_partial/scripts/index') %>
    37|       <% if (theme.plugins.pjax.enable){ %>
    38|         <%- partial('_plugins/pjax/index') %>
    39|       <% } %>

E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\layout\_partial\scripts\index.ejs:146
    144|
    145| <% if (theme.structured_data && theme.structured_data.enable) { %>
 >> 146|   <%- structured_data() %>
    147| <% } %>
    148|
    149|

Incorrect locale information provided
    at new DateTimeFormat (<anonymous>)
    at module.exports (E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\breadcrumblist.js:68:19)
    at E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\index.js:28:52
    at Array.map (<anonymous>)
    at module.exports (E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\index.js:28:41)
    at eval ("E:\\Personal_Profile\\Blog\\node_modules\\hexo-theme-volantis\\layout\\_partial\\scripts\\index.ejs":267:17)
    at index (E:\Personal_Profile\Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:120:32)
    at _View.renderSync (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:62:29)
    at Object.partial (E:\Personal_Profile\Blog\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("E:\\Personal_Profile\\Blog\\node_modules\\hexo-theme-volantis\\layout\\layout.ejs":65:17)
    at layout (E:\Personal_Profile\Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:123:67)
    at _View.render (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:48:21)
    at E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:55:31
    at tryCatcher (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\async.js:86:9)
ERROR
RangeError: E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\layout\layout.ejs:36
    34|     </div>
    35|     <div>
 >> 36|       <%- partial('_partial/scripts/index') %>
    37|       <% if (theme.plugins.pjax.enable){ %>
    38|         <%- partial('_plugins/pjax/index') %>
    39|       <% } %>

E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\layout\_partial\scripts\index.ejs:146
    144|
    145| <% if (theme.structured_data && theme.structured_data.enable) { %>
 >> 146|   <%- structured_data() %>
    147| <% } %>
    148|
    149|

Incorrect locale information provided
    at new DateTimeFormat (<anonymous>)
    at module.exports (E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\breadcrumblist.js:68:19)
    at E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\index.js:28:52
    at Array.map (<anonymous>)
    at module.exports (E:\Personal_Profile\Blog\node_modules\hexo-theme-volantis\scripts\helpers\structured-data\lib\index.js:28:41)
    at eval ("E:\\Personal_Profile\\Blog\\node_modules\\hexo-theme-volantis\\layout\\_partial\\scripts\\index.ejs":267:17)
    at index (E:\Personal_Profile\Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:120:32)
    at _View.renderSync (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:62:29)
    at Object.partial (E:\Personal_Profile\Blog\node_modules\hexo\dist\plugins\helper\partial.js:27:17)
    at eval ("E:\\Personal_Profile\\Blog\\node_modules\\hexo-theme-volantis\\layout\\layout.ejs":65:17)
    at layout (E:\Personal_Profile\Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:123:67)
    at _View.render (E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:48:21)
    at E:\Personal_Profile\Blog\node_modules\hexo\dist\theme\view.js:55:31
    at tryCatcher (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Personal_Profile\Blog\node_modules\bluebird\js\release\async.js:86:9)

### 配置文件

<details><summary>站点配置文件</summary><p>

```yml
在这里粘贴替换 `blog/_config.yml` 中修改过的部分
```

</p></details>

<details><summary>主题配置文件</summary><p>

```yml
在这里粘贴替换 `themes/volantis/_config.yml` 中修改过的部分
```

</p></details>

### 环境信息

<details><summary>node.js & npm</summary><p>

```
node -v && npm -v
v20.12.0
10.5.0
```

</p></details>

<details><summary>package.json</summary><p>

```
C:\Users\AyMeow~>npm ls --depth 0
C:\Users\AyMeow~
`-- (empty)
```

</p></details>

**Comment by inkss** [comment]
```
Incorrect locale information provided
  at new DateTimeFormat ()
```

config.language 是怎么配置的？在  `blog/_config.yml` 文件中。

**Comment by kibabuuuuaua** [comment]
解决了吗？我也是一样

**Comment by ayellowdogsays** [comment]
可能是插件没装全吧
